# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andy cesty
author: sajdoann
email: sajdokova@gmail.com
github_username:  sajdoann # DO NOT include the @ character, or else the build will fail!
locale: cs-CZ


logo: /favicons/android-chrome-384x384.png
read_time: true
words_per_minute: 200

paginate: 10  # amount of posts to show per page
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji
  - jekyll-remote-theme

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/
    sort_by: date
    sort_order: reverse

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_recipes"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # blogs defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: false

exclude: [LICENSE-CODE.md, LICENSE-IMAGES, README.md, bower.json]


# Site Author
author: 
  name: Anna Sajdoková
  picture: images/isc_sajdokova.png
  email: sajdokova@gmail.com
  # twitter:
  links:
    - title: Instagram
      url: https://instagram.com/sajdoann
      icon: fa fa-instagram
    - title: GitHub
      url: https://github.com/sajdoann
      icon: fa fa-github-square
    - title: Facebook
      url: https://facebook.com/sajdoann
      icon: fa fa-facebook-square

# Footer Links
footer_links:
 - title: Instagram
   url: https://instagram.com/sajdoann
   icon: fa fa-instagram
 - title: GitHub
   url: https://github.com/sajdoann
   icon: fa fa-github-square
 - title: Facebook
   url: https://facebook.com/sajdoann
   icon: fa fa-facebook-square


